<?php
//
// File generated by Dolibarr installer 3.6.5 on 14 Déc. 2015
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
$dolibarr_main_url_root='http://localhost/cesgm/htdocs';
$dolibarr_main_document_root='/Applications/XAMPP/xamppfiles/htdocs/cesgm/htdocs';
//$dolibarr_main_url_root_alt='/custom';
//$dolibarr_main_document_root_alt='/Applications/XAMPP/xamppfiles/htdocs/cesgm/htdocs/custom';
$dolibarr_main_data_root='/Applications/XAMPP/xamppfiles/htdocs/cesgm/documents';
$dolibarr_main_db_host='localhost';
$dolibarr_main_db_port='';
$dolibarr_main_db_name='prunur96_cesgm';
$dolibarr_main_db_prefix='test_';
$dolibarr_main_db_user='prunur96_cesgmU';
$dolibarr_main_db_pass='Prunus321@';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='latin1';
$dolibarr_main_db_collation='latin1_swedish_ci';
$dolibarr_main_authentication='dolibarr';

// Specific settings
$dolibarr_main_prod='0';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_force_https='0';
$dolibarr_main_cookie_cryptkey='efe351294c7157abcd95491a39003206';
$dolibarr_mailing_limit_sendbyweb='0';

//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_lib_FPDF_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_ADODB_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_PHPEXCEL_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';
//$dolibarr_js_JQUERY_FLOT='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
?>